In [1]:
import pandas as pd
from pathlib import Path

In [2]:
#store filepaths as a variable
file1 = Path("Resources/202404-citibike-tripdata.csv")

In [5]:
#read data files with pandas library
file1_df = pd.read_csv(file1, low_memory=False)

In [6]:
file1_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,F561526822C9D60B,electric_bike,2024-04-27 13:56:13.940,2024-04-27 14:05:23.629,FDR Drive & E 35 St,6230.04,E 10 St & 2 Ave,5746.02,40.743955,-73.971391,40.729708,-73.986598,member
1,359BAF91507F4998,electric_bike,2024-04-25 15:23:14.529,2024-04-25 15:27:52.895,Forsyth St & Grand St,5382.07,E 10 St & 2 Ave,5746.02,40.717741,-73.993388,40.729708,-73.986598,member
2,AAEE95A1C0106C97,electric_bike,2024-04-06 11:15:18.132,2024-04-06 11:22:10.081,E 20 St & 2 Ave,5971.08,Mott St & Prince St,5561.04,40.735790,-73.981693,40.723180,-73.994800,member
3,95B077C9C619D404,electric_bike,2024-04-06 16:19:25.749,2024-04-06 16:21:43.098,Eastern Pkwy & Washington Ave,3928.08,Eastern Pkwy & Franklin Ave (SW Corner),3919.12,40.671649,-73.963115,40.670529,-73.958222,member
4,1A33C864454C4692,electric_bike,2024-04-10 17:40:14.700,2024-04-10 17:48:11.571,W 27 St & 6 Ave,6215.07,E 25 St & 1 Ave,6004.07,40.745446,-73.990591,40.738177,-73.977387,member

In [9]:
row_count = file1_df.shape[0]
print(row_count)

3217063

In [11]:
cleaned_file1_df = file1_df.dropna()
cleaned_file1_df.tail()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
3217058,BE0F887BE16DFDDA,electric_bike,2024-04-16 07:47:35.966,2024-04-16 07:54:57.079,Atlantic Ave & Furman St,4614.04,Clark St & Henry St,4789.03,40.691736,-74.000174,40.697601,-73.993446,member
3217059,850F33001EDD1AE4,classic_bike,2024-04-10 08:45:16.500,2024-04-10 08:51:55.652,E 63 St & 3 Ave,6830.02,E 44 St & Lexington Ave,6464.09,40.763954,-73.964600,40.752643,-73.974996,member
3217060,CEE1CDE84344E8FF,electric_bike,2024-04-09 17:44:45.398,2024-04-09 18:03:46.293,Atlantic Ave & Furman St,4614.04,E 5 St & Cooper Sq,5712.12,40.691729,-74.000147,40.727690,-73.990993,member
3217061,174E104B28274EE1,classic_bike,2024-04-03 14:42:57.301,2024-04-03 14:51:34.967,W 48 St & Rockefeller Plaza,6626.11,W 20 St & 5 Ave,6098.02,40.757769,-73.979294,40.739730,-73.991040,member
3217062,F17B1138A0D1497F,classic_bike,2024-04-25 11:38:01.936,2024-04-25 11:40:29.875,Henry St & Middagh St,4861.05,Clark St & Henry St,4789.03,40.700300,-73.991581,40.697601,-73.993446,member

In [13]:
row_count = cleaned_file1_df.shape[0]
print(row_count)

3209060

In [15]:
sample_202404_df = cleaned_file1_df.sample(frac=0.05)

In [17]:
row_count = sample_202404_df.shape[0]
print(row_count)

160453

In [19]:
#export file as csv
sample_202404_df.to_csv("Resources/ny_citibike_202404.csv", index=False, header=True)